productspotlight_conf_form:
  path: /ek_productspotlight/search
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\Ek_ProductSpotlight\Controller\ProductspotlightController::index'
    # Needed to work with tab system
    _legacy_controller: AdminEk_ProductSpotlight
    _legacy_link: AdminEk_ProductSpotlight
