spotlightproduct_conf_form:
  path: /spotlightproduct/search
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\Spotlightproduct\Controller\SpotlightproductController::index'
    # Needed to work with tab system
    _legacy_controller: AdminSpotlightproduct
    _legacy_link: AdminSpotlightproduct
