services:
  _defaults:
    public: true

  # Demo configuration text form
  prestashop.module.spotlightproduct.form.type.spotlightproduct_text:
    class: 'PrestaShop\Module\Spotlightproduct\Form\SpotlightproductFormType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  prestashop.module.spotlightproduct.form.spotlightproduct_text_data_configuration:
    class: 'PrestaShop\Module\Spotlightproduct\Form\SpotlightproductTextDataConfiguration'
    arguments: ["@prestashop.adapter.legacy.configuration"]

  prestashop.module.spotlightproduct.form.spotlightproduct_text_form_data_provider:
    class: 'PrestaShop\Module\Spotlightproduct\Form\SpotlightproductTextFormDataProvider'
    arguments:
      - '@prestashop.module.spotlightproduct.form.spotlightproduct_text_data_configuration'

  prestashop.module.spotlightproduct.form.spotlightproduct_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.spotlightproduct.form.spotlightproduct_text_form_data_provider'
      - 'PrestaShop\Module\Spotlightproduct\Form\SpotlightproductFormType'
      - 'Configuration'

  PrestaShop\Module\Spotlightproduct\Controller\SpotlightproductController:
    # Using autowire will inject services in the constructors automatically
    autowire: true
    # Using autoconfigure with controllers that extend AbstractController will handle method parameter injection and subscribed services
    autoconfigure: true
    # If your controller class doesn't extend AbstractController you should add this tag manually so you benefit from method parameters injection
    tags: ['controller.service_arguments']